<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Already Signed Up? Click {link} to login your account.' => 'Bạn đã có tài khoản? Truy cập đường dẫn {link} để đăng nhập.',
    'Confirmation' => 'Xác nhận mật khẩu.',
    'I read {link}.' => 'Tôi đã đọc {link}',
    'Password' => 'Mật khẩu',
    'Register' => 'Đăng ký',
    'Sign In' => 'đăng nhập',
    'Sign up' => 'Đăng ký',
    'Terms and Conditions' => 'Điều khoản và điều kiện',
    'Username' => 'Username',
];
